SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS
INNER JOIN 
(SELECT *
FROM ANIMAL_INS
WHERE 
SEX_UPON_INTAKE LIKE 'Intact %') AS ANIMAL
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL.ANIMAL_ID
WHERE SEX_UPON_OUTCOME NOT LIKE 'Intact %'

ORDER BY ANIMAL_ID